'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.18444
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Tooltip
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("mod_kit.Tooltip", GetType(Tooltip).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類似 ArmorStatusHUD可以顯示出你身上裝備的耐久度 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property ArmorStatusHUD() As String
            Get
                Return ResourceManager.GetString("ArmorStatusHUD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 bspkrsCore是裝其他bspkrs製作的模組需要的前置模組 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property bspkrsCore() As String
            Get
                Return ResourceManager.GetString("bspkrsCore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 CodeChickenCore是裝Not Enough Items所需要的前置模組 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property CodeChickenCore() As String
            Get
                Return ResourceManager.GetString("CodeChickenCore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 CraftGuide可以讓你在遊戲中查詢合成表，預設按下G鍵可以開啟介面 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property CraftGuide() As String
            Get
                Return ResourceManager.GetString("CraftGuide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 Damage Indicators可以顯示生物、玩家的血量以及受到的藥水效果 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Damage_Indicators() As String
            Get
                Return ResourceManager.GetString("Damage_Indicators", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 DirectionHUD在畫面上方會顯示出方位 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property DirectionHUD() As String
            Get
                Return ResourceManager.GetString("DirectionHUD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 Forge是很多模組需要的前置API，有90%↑的模組需要/支援Forge 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Forge() As String
            Get
                Return ResourceManager.GetString("Forge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 iChun Util是裝iChun所製作的模組的前置模組 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property iChun_Util() As String
            Get
                Return ResourceManager.GetString("iChun_Util", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 InGameInfoXML可以顯示出時間(以現實時間的方式來讓你知道現在遊戲的時間)、所處的生態系、亮度、經驗等等 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property InGameInfoXML() As String
            Get
                Return ResourceManager.GetString("InGameInfoXML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 Inventory Tweaks可以快速整理你凌亂的包包預設按下R鍵可以快速整理 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Intevtory_Tweaks() As String
            Get
                Return ResourceManager.GetString("Intevtory_Tweaks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 LunatriusCore是裝InGameInfoXML的前置模組 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property LunatriusCore() As String
            Get
                Return ResourceManager.GetString("LunatriusCore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 Mob Amputation是和Mob Dismemberment搭配的模組，打一些生物時會有身體分解、噴血的效果
        '''
        '''在單人如果骷髏弓箭手拿弓的手被打斷了他會直接衝過來打你 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Mob_Amputation() As String
            Get
                Return ResourceManager.GetString("Mob_Amputation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 Mob Dismemberment是和Mob Amputation搭配的模組，打一些生物時會有身體分解、噴血的效果
        '''
        '''在單人如果骷髏弓箭手拿弓的手被打斷了他會直接衝過來打你 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Mob_Dismemberment() As String
            Get
                Return ResourceManager.GetString("Mob_Dismemberment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 Not Enough Items是一款很強大的模組，在安裝之後進入遊戲打開E鍵就會發現很大的改變
        '''
        '''右邊的方塊/物品在Cheat mode的時候可以拿出來(如果是單人遊戲或你是伺服的OP)
        '''
        '''游標放在方塊/物品上按R鍵可以看到方塊/物品怎麼合成而來
        '''
        '''游標放在方塊/物品上按U鍵可以看到方塊/物品可以合成出什麼
        '''
        ''' 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Not_Enough_Items() As String
            Get
                Return ResourceManager.GetString("Not_Enough_Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 Rei&apos;s Minimap是一款地圖模組，可以顯示出玩家附近的地形、生物等等，也可以標記地點(例如自己的家)作為引導
        '''
        '''*相較於Voxelmap，沒有礦道地圖，預設在多人也沒有辦法顯示生物 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Rei_s_Minimap() As String
            Get
                Return ResourceManager.GetString("Rei_s_Minimap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 StatusEffectHUD可以讓你方便看到自己現在受到那些藥水狀態影響 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property StatusEffectHUD() As String
            Get
                Return ResourceManager.GetString("StatusEffectHUD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 Voxelmap是一款地圖模組，可以顯示出玩家附近的地形(洞窟內也可以)、生物等等，也可以標記地點(例如自己的家)作為引導 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Voxelmap() As String
            Get
                Return ResourceManager.GetString("Voxelmap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 Waila會在畫面上方顯示物品的提示(方塊名稱)，如果你有裝了新增方塊的模組，當你畫面滑過時還可以看到是哪個模組的方塊 的當地語系化字串。
        '''</summary>
        Friend Shared ReadOnly Property Waila() As String
            Get
                Return ResourceManager.GetString("Waila", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
